### ISSUE TITLE
Enhancement: Add a LICENSE

### ISSUE THREAD

**Issue by bollwyvl** [litestar-org/litestar-htmx#7]
### Summary

As there is no `LICEN[CS]E(.txt)?` in this repo, it is also missing from the sdist and wheel on github. The `pyproject.toml` also does not provide a trove classifier, nor a link to this repo.

### Basic Example

Copy the LICENSE from `litestar`?

### Drawbacks and Impact

n/a

### Unresolved questions

n/a

**Comment by cofin** [comment]
Closed by #8
